spring.application.name=BloodLink
spring.datasource.url=jdbc:mysql://localhost:3306/BloodLink
spring.datasource.username=root
spring.datasource.password=Dop.mi3871300100017

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true